/gazebo_ros_control:
  pid_gains:
    arm_joint_1:
      p: 100
      i: 1
      d: 0
    arm_joint_2:
      p: 100
      i: 1
      d: 0
    arm_joint_3:
      p: 100
      i: 1
      d: 0
    arm_joint_4:
      p: 100
      i: 10
      d: 0
    arm_joint_5:
      p: 100
      i: 1
      d: 0
