youbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  #joint0_position_controller:
  # type: position_controllers/JointPositionController
  # joint: arm_joint_0
  # pid: {p: 100.0, i: 0.01, d: 10.0}
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_joint_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_joint_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_joint_3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_joint_4
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: arm_joint_5
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_r_position_controller:
    type: position_controllers/JointPositionController
    joint: gripper_finger_joint_r
    pid: {p: 100.0, i: 0.01, d: 10.0}
  gripper_l_position_controller:
    type: position_controllers/JointPositionController
    joint: gripper_finger_joint_l
    pid: {p: 100.0, i: 0.01, d: 10.0}

